### ISSUE TITLE
Hunt down Neisseria meniningitidis β1–4 Galactosyltransferase gene

### ISSUE THREAD

**Issue by TheLostLambda** [Sheffield-iGE/rEvolver#44]

**Comment by TheLostLambda** [comment]
From Izzy:

- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3114949/

Might be an example of the enzyme being overexpressed in __

**Comment by RikkiD** [comment]
I have found another paper on galactosyltransferase but it mentions a lot of other information that may be entirely irrelevant and the stuff about the actual enzyme seems to be in your original paper. Let me know if this is on the right path or what else I should be focusing on.

https://doi.org/10.1016/j.bmc.2016.02.043

**Comment by TaylorCWR** [comment]
Both the Neisseria and Helicobacter ORFs have been found! 

https://docs.google.com/spreadsheets/d/1U0o4rRijpZ9DH6L4je8-XVgZwBWw6sROZ0GAiCq9xro/edit?pli=1#gid=0

**Comment by TaylorCWR** [comment]
close!
