### ISSUE TITLE
Contact Uni about research stipend for members

### ISSUE THREAD

**Issue by TheLostLambda** [Sheffield-iGE/rEvolver#5]

**Comment by TaylorCWR** [comment]
Emailed Rosie Staniforth about funding of the 7 MBB students! Seeing what she says and then going to other departments after that :)

**Comment by TaylorCWR** [comment]
Andy says this is unlikely...

**Comment by TheLostLambda** [comment]
This is looking not super possible... Let me know if we can sort anything out here, but I'll close for now
