### ISSUE TITLE
Planning experiments: V. natriegens growth on M9 alone; M9 + Sorbitol; M9 + Sorbitol + Glucose; Sorbitol alone

### ISSUE THREAD

**Issue by alxconnolly** [Sheffield-iGE/rEvolver#86]

**Comment by TaylorCWR** [comment]
https://benchling.com/sheffield-igem-org/f/lib_tlGSuikA-testing-growth-on-sorbitol-sugar/prt_2ZCqkVsu-testing-v-natriegens-growth-on-sorbitol/edit
